models/associate.py
from sqlalchemy import Column, String, ForeignKey, Table

from models.base import Base


pizza_ingred_assoc_table = Table(
    "pizza_ingred_assoc_table",
    Base.metadata,
    Column("pizza_id", ForeignKey("pizzas.id"), primary_key=True),
    Column("ingredient_id", ForeignKey("ingredients.id"), primary_key=True)
)

models/base.py
from sqlalchemy.orm import DeclarativeBase, sessionmaker
from sqlalchemy import create_engine


engine = create_engine("sqlite:///pizzas.db", echo=True)
Session = sessionmaker(bind=engine)


class Base(DeclarativeBase):
    pass


def create_db():
    Base.metadata.create_all(bind=engine)


def drop_db():
    Base.metadata.drop_all(bind=engine)

models/ingredient.py
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String

from models.base import Base


class Ingredient(Base):
    __tablename__ = "ingredients"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(50))

models/pizza.py
from typing import List

from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String

from models.base import Base
from models.ingredient import Ingredient
from models.associate import pizza_ingred_assoc_table


class Pizza(Base):
    __tablename__ = "pizzas"

    id: Mapped[int] = mapped_column("id", primary_key=True)
    name: Mapped[str] = mapped_column(String(50))
    price: Mapped[float] = mapped_column()
    ingredients: Mapped[List[Ingredient]] = relationship(secondary=pizza_ingred_assoc_table)

main.py
from flask import Flask

from routes.pizza import pizza_route
from models.pizza import Pizza
from models.ingredient import Ingredient
from models.base import create_db


app = Flask(__name__)
app.register_blueprint(pizza_route)


if __name__ == "__main__":
    create_db()
    app.run(debug=True)

routes/pizza.py
from flask import Blueprint, render_template, request, redirect

from models.base import Session
from models.pizza import Pizza
from models.ingredient import Ingredient
from data.wheather import get_wheather
from flask import render_template
from flask import Flask, url_for, redirect


pizza_route = Blueprint("pizzas", __name__)


@pizza_route.get("/")
def index():
    wheather = get_wheather("Neratovice")
    temp = wheather.get("temp")
    pizza_name = "Невідома піцца"
    if temp is not None:
        if 26 > temp > 10:
            pizza_name = "Тепла"
        elif temp <= 10:
            pizza_name = "Холодна"
        elif temp > 26:
            pizza_name = "Пепероні"


    return render_template("index.html", title="Моя супер піцерія", wheather=wheather, pizza_name=pizza_name)


@pizza_route.get("/menu/")
def menu():
    wheather = get_wheather("Kyiv")
    with Session() as session:
        pizzas = session.query(Pizza).all()
        ingredients = session.query(Ingredient).all()

        context = {
            "pizzas": pizzas,
            "ingredients": ingredients,
            "title": "Мега меню",
            "wheather": wheather
        }
        return render_template("menu.html", **context)


@pizza_route.post("/add_pizza/")
def add_pizza():
    with Session() as session:
        name = request.form.get("name")
        price = request.form.get("price")
        ingredients = request.form.getlist("ingredients")
        ingredients = session.query(Ingredient).where(Ingredient.id.in_(ingredients)).all()

        pizza = Pizza(name=name, price=price, ingredients=ingredients)
        session.add(pizza)
        session.commit()
        return redirect("/menu/")
    


@pizza_route.get("/pizza/del/<int:id>/")
def del_pizza(id):
    with Session() as session:
        pizza = session.query(Pizza).where(Pizza.id == id).first()
        session.delete(pizza)
        session.commit()
        return redirect(url_for("pizzas.menu"))


@pizza_route.get("/pizza/edit/<int:id>/")
@pizza_route.post("/pizza/edit/<int:id>/")
def edit_pizza(id):
    with Session() as session:
        pizza = session.query(Pizza).where(Pizza.id == id).first()
        if request.method == "POST":
            title = request.form.get("title")
            text = request.form.get("text")

            pizza.title = title
            pizza.text = text
            session.commit()
            return redirect(url_for("pizza.index"))

        return render_template("edit_pizza.html", pizza=pizza)

templates/_base.html
{# "templates/_base.html" #}

{% import "_macros.html" as macros %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/style.css">
    <title>
        {% block title %}
        {{ title }}
        {% endblock title %}
    </title>
</head>
<body>
    {% include "_navigation.html" %}
    <br>

    <br><br><br>

    {% block content %}
    {% endblock content %}

    <footer><br><button>{{ macros.light_or_dark_mode("body") }}</button></footer>
</body>
</html>

templates/_macros.html
{# templates/macros.html #}

{% macro light_or_dark_mode(element) %}

{% if request.args.get('mode') == "dark" %}

<a href="{{ request.path }}">Перемкнути на світлу тему</a>

<style>
    {{ element }} {
    background-color: #212F3C;
    color: #FFFFF0;
    }
    {{ element }} a {
    color: #00BFFF !important;
    }
</style>
{% else %}
<a href="{{ request.path }}?mode=dark">Перемкнути на темну тему</a>
{% endif %}

{% endmacro %}

{% macro sort_price(pizzas) %}

<table>
    <tr>
        <th>Назва піци</th>
        <th>Склад</th>
        <th>Ціна</th>
    </tr>
    {% if request.args.get("sort") %}
    <a href="{{ request.path }}">Вимкнути сортування</a>

        {% for pizza in pizzas|sort(attribute="price") %}
        <tr>
            <td>{{ pizza.name }}</td>
            <td>{{ pizza.ingredients }}</td>
            <td>{{ pizza.price }}</td>
        </tr>
        {% endfor %}

    {% else %}
    <a href="{{ request.path }}?sort=True">Увімкнути сортування</a>
        {% for pizza in pizzas %}
        <tr>
            <td>{{ pizza.name }}</td>
            <td>{{ pizza.ingredients }}</td>
            <td>{{ pizza.price }}</td>
        </tr>
        {% endfor %}
    {% endif %}
</table>

{% endmacro %}

templates/_navigation.html
{# "templates/_navigation.html" #}

<nav>
{% for menu_item in ["pizzas.index", "pizzas.menu"] %}
<button>
    <a href="{{ url_for(menu_item) }}">{{ menu_item|upper }}</a>
</button>
{% endfor %}
</nav>

templates/_wheather.html
<div>
    <h1>Місто: <em>{{ wheather.city }}</em></h1>
    <h2>Температура: {{ wheather.temp }}°</h2>
    <h3>{{ wheather.text }}</h3>
    <img src="{{ wheather.icon }}">
</div>

templates/edit_pizza.html
{% extends "_base.html" %}

{% block content %}
<form action="{{ url_for('pizzas.add_pizza')}}" method="post">
    <p>
        <label>Назва піци</label>
        <input type="text" name="name">
    </p>
    <p>
        <label>Ціна</label>
        <input type="number" name="price">
    </p>
    <p>
     
    <button type="submit">Додати піцу</button>
</form>

{% endblock content %}

templates/index.html
{# "templates/index.html" #}

{% extends "_base.html" %}

{% block content %}
{% include "_wheather.html" %}
<h1><p>Пропонуємо таку піцу: <em>{{ pizza_name }}</em></p></h1>
{% endblock content %}
<a type="button", href="/menu"><em>Перейти в Мега меню</em></button>

templates/menu.html
{# "templates/menu.html" #}

{% extends "_base.html" %}

{% block content %}
{% include "_wheather.html" %}
<table>
    <tr>
        <th>№</th>
        <th>Назва піци</th>
        <th>Ціна</th>
        <th>Інгредієнти</th>
    </tr>
    {% for pizza in pizzas %}
        <tr>
            <td>{{ pizza.id }}</td>
            <td>{{ pizza.name }}</td>
            <td>{{ pizza.price }}</td>
            <td>
                {% for ingredient in pizza.ingredients %}
                    {{ ingredient.name }}|
                {% endfor %}
            </td>
        <td>
        <a href="{{ url_for('pizzas.edit_pizza', id=pizza.id) }}" class="btn btn-info" >Редагувати піццу</a>
        <a href="{{ url_for('pizzas.del_pizza', id=pizza.id) }}" class="btn btn-danger">Видалити піццу</a>
    </td>
    {% endfor %}</tr>
</table>

<form action="{{ url_for('pizzas.add_pizza')}}" method="post">
    <p>
        <label>Назва піци</label>
        <input type="text" name="name">
    </p>
    <p>
        <label>Ціна</label>
        <input type="number" name="price">
    </p>
    <p>
     
    <button type="submit">Додати піцу</button>
</form>

{% endblock content %}